#!/usr/bin/env python3
"""Generate dev-variant icons from src-tauri/icons/icon.png.

Stamps a bold orange "DEV" badge in the bottom-right of the squircle so the
running debug binary is visually distinct from the installed release. Output
sizes mirror the prod icon set declared in `bundle.icon`.
"""
from __future__ import annotations

import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src-tauri" / "icons" / "icon.png"
OUT_DIR = ROOT / "src-tauri" / "icons"

DEV_PNG_SIZES: dict[str, int] = {
    "icon-dev.png": 512,
    "icon-dev-32x32.png": 32,
    "icon-dev-64x64.png": 64,
    "icon-dev-128x128.png": 128,
    "icon-dev-128x128@2x.png": 256,
}

# Slightly muted, high-contrast orange that reads "DEV" without screaming.
BADGE_COLOR = (255, 122, 0, 255)
BADGE_OUTLINE = (12, 12, 12, 255)


def font_for(px: int) -> ImageFont.FreeTypeFont | ImageFont.ImageFont:
    candidates = [
        "/System/Library/Fonts/Supplemental/Arial Bold.ttf",
        "/System/Library/Fonts/HelveticaNeue.ttc",
        "/System/Library/Fonts/SFNS.ttf",
    ]
    for path in candidates:
        if Path(path).exists():
            try:
                return ImageFont.truetype(path, px)
            except OSError:
                continue
    return ImageFont.load_default()


def stamp_dev_badge(src: Image.Image) -> Image.Image:
    """Render the badge at 1024px then downscale to 512px for crisp edges."""
    work = src.convert("RGBA").resize((1024, 1024), Image.LANCZOS)
    overlay = Image.new("RGBA", work.size, (0, 0, 0, 0))
    draw = ImageDraw.Draw(overlay)

    # Circular badge inset from the bottom-right corner of the squircle.
    # 1024 work canvas; the squircle's bottom-right curve ends at roughly
    # (944, 944) so we centre the badge at (768, 768) with a 220px radius.
    cx, cy, r = 768, 768, 220
    draw.ellipse(
        (cx - r, cy - r, cx + r, cy + r),
        fill=BADGE_COLOR,
        outline=BADGE_OUTLINE,
        width=14,
    )

    text = "DEV"
    font = font_for(180)
    bbox = draw.textbbox((0, 0), text, font=font)
    tw, th = bbox[2] - bbox[0], bbox[3] - bbox[1]
    draw.text(
        (cx - tw / 2 - bbox[0], cy - th / 2 - bbox[1]),
        text,
        font=font,
        fill=(255, 255, 255, 255),
        stroke_width=6,
        stroke_fill=BADGE_OUTLINE,
    )

    composed = Image.alpha_composite(work, overlay)
    return composed.resize((512, 512), Image.LANCZOS)


def write_pngs(base: Image.Image) -> None:
    for name, size in DEV_PNG_SIZES.items():
        out = base if size == base.width else base.resize((size, size), Image.LANCZOS)
        path = OUT_DIR / name
        out.save(path, format="PNG")
        print(f"wrote {path.relative_to(ROOT)} ({size}x{size})")


def write_ico(base: Image.Image) -> None:
    path = OUT_DIR / "icon-dev.ico"
    base.save(
        path,
        format="ICO",
        sizes=[(16, 16), (32, 32), (48, 48), (64, 64), (128, 128), (256, 256)],
    )
    print(f"wrote {path.relative_to(ROOT)}")


def main() -> int:
    if not SRC.exists():
        print(f"missing {SRC}", file=sys.stderr)
        return 1
    base = stamp_dev_badge(Image.open(SRC))
    write_pngs(base)
    write_ico(base)
    print("done. icns is generated by scripts/make-dev-icns.sh (needs iconutil).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
